# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
builds:
  -
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
